version: "3"
services:
  web:
    image: 'frontend'
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
  tests:
    image: 'frontend'
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]